# Configurations
title:            IHI Open School Online - QI 104
longtitle:        Notes for QI 104 Interpreting Data Run Charts, Control Charts
author:           Ali Alohali
description: >
  The page contains my notes for QI 104: Interpreting Data: Run Charts, Control Charts, and Other Measurement Tools course by Institute for Healthcare Improvement.

version:          1.0
gitbook_version:  3.2.3

url:              ''
baseurl:          '/IHI-QI104'
rss:              RSS

google_analytics: UA-134016492-1

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
